"""create exerciseTemplate table and update exercise table

Revision ID: dfb64812a775
Revises: 8cf274db5edb
Create Date: 2025-10-18 16:20:20.626567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb64812a775'
down_revision = '8cf274db5edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('exercise_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_templates_muscle_group'), ['muscle_group'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_template_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'exercise_templates', ['exercise_template_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('exercise_template_id')

    with op.batch_alter_table('exercise_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_templates_muscle_group'))

    op.drop_table('exercise_templates')
    # ### end Alembic commands ###
